### ISSUE TITLE
Fix redirect to localhost when login

### ISSUE THREAD

**Issue by n2shh** [midudev/midufest#26]
When logging in by clicking on get ticket button upon signing in with GitHub, it redirects to localhost:3000
![image](https://user-images.githubusercontent.com/98247987/218242495-6fd21c82-6c6f-4ec9-ad80-11ab2b90ad2c.png)
-
![image](https://user-images.githubusercontent.com/98247987/218242509-d400fae9-252d-4b97-8066-f63573871325.png)

**Comment by daesdev** [comment]
Copy and paste the access token into midufest.com/{hash}, the platform registration is left with the number one ticket 
<img width="743" alt="image" src="https://user-images.githubusercontent.com/31475869/218618130-321f9cbf-3643-4ae4-b566-df2c43916899.png">
